#!/bin/bash
echo ffmpeg -i $1 -f webm -vcodec libvpx -acodec libvorbis -crf 4 -b:v 1M -vf subtitles=$1 -threads 0 -ss $3 -t $4 $2
ffmpeg -i $1 -threads 0 -f webm -c:v libvpx -c:a libvorbis -sn -crf 4 -b:v 1M -vf subtitles=$1 -ss $2 -t $3 "$1".webm
